default:
	python kp_models/kp.py
	python kp_models/kpL1.py
	python kp_models/kpL2.py
	python angle_models/ang.py
	python angle_models/angL1.py
	python angle_models/angL2.py

clean:
	rm -rf */*.pt */__*