default:
	# keypoint models
	python kp_models/kp.py
	python kp_models/kpL1.py
	python kp_models/kpL2.py
	# angle models
	python angle_models/ang.py
	python angle_models/angL1.py
	python angle_models/angL2.py
	# mixed models
	python mixed_models/mixed.py
	python mixed_models/mixedL1.py
	python mixed_models/mixedL2.py

clean:
	rm -rf */*.pt */__* *.pt *.blacke